    - name: Install VLC media player
      apt: pkg=vlc
      become: yes

    - name: Add spotify apt key
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=BBEBDCB318AD50EC6865090613B00F1FD2C19886
      become: yes

    - name: Add spotify repository
      apt_repository: repo="deb http://repository.spotify.com stable non-free"
      become: yes

    - name: Install spotify client
      apt: pkg=spotify-client update_cache=yes
      become: yes

    - name: Install handbrake video converter
      apt: pkg=handbrake
      become: yes

    - name: Install k3b optical disk authoring tool
      apt: pkg=k3b
      become: yes

    - name: Install GIMP photo editor
      apt: pkg=gimp
      become: yes

    - name: Install shutter screenshot tool
      apt: pkg=shutter
      become: yes
