    - name: Determine if laptop
      command: laptop-detect
      register: is_laptop
      ignore_errors: yes

    - name: Remove Totem media player
      apt: pkg=totem state=absent
      become: yes

    - name: Install VLC media player
      apt: pkg=vlc
      become: yes

    - name: Install Clementine music player
      apt: pkg=clementine
      become: yes

    - name: Remove rhythmbox music player
      apt: pkg=rhythmbox state=absent
      become: yes

    - name: Install handbrake video converter
      apt: pkg=handbrake
      become: yes

    - name: Install k3b optical disk authoring tool
      apt: pkg=k3b
      when: is_laptop|failed
      become: yes

    - name: Install GIMP photo editor
      apt: pkg=gimp
      become: yes

    - name: Install shutter screenshot tool
      apt: pkg=shutter
      become: yes
